# Generated by Django 4.1.2 on 2022-10-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_img', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_img', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
            ],
        ),
    ]
