# Generated by Django 4.1.2 on 2022-11-25 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucas.cart')),
            ],
        ),
    ]
