# Generated by Django 4.1.3 on 2022-12-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucas', '0002_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('is_create_account', models.BooleanField(default=False)),
                ('order_notes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddressCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucas.billingaddress')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucas.checkout')),
            ],
        ),
    ]
